### ISSUE TITLE
cli skeleton

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/samples-filter#1]
Let's implement https://github.com/yegor256/cam/issues/227 in this repository, by packing project as Python command-line application, that can be installed using [pip](https://pip.pypa.io/en/stable/cli/pip_install/) from [PyPI](https://pypi.org).

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#9](https://github.com/h1alexbel/samples-filter/issues/9) is still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#10](https://github.com/h1alexbel/samples-filter/issues/10), [#11](https://github.com/h1alexbel/samples-filter/issues/11), [#9](https://github.com/h1alexbel/samples-filter/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 4 puzzles [#10](https://github.com/h1alexbel/samples-filter/issues/10), [#11](https://github.com/h1alexbel/samples-filter/issues/11), [#14](https://github.com/h1alexbel/samples-filter/issues/14), [#9](https://github.com/h1alexbel/samples-filter/issues/9) are still not solved.

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.01`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#10](https://github.com/h1alexbel/samples-filter/issues/10), [#11](https://github.com/h1alexbel/samples-filter/issues/11), [#9](https://github.com/h1alexbel/samples-filter/issues/9) are still not solved; solved: [#14](https://github.com/h1alexbel/samples-filter/issues/14).

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#18](https://github.com/h1alexbel/samples-filter/issues/18), [#19](https://github.com/h1alexbel/samples-filter/issues/19), [#9](https://github.com/h1alexbel/samples-filter/issues/9) are still not solved; solved: [#10](https://github.com/h1alexbel/samples-filter/issues/10), [#11](https://github.com/h1alexbel/samples-filter/issues/11), [#14](https://github.com/h1alexbel/samples-filter/issues/14).

**Comment by 0pdd** [comment]
@h1alexbel 5 puzzles [#18](https://github.com/h1alexbel/samples-filter/issues/18), [#22](https://github.com/h1alexbel/samples-filter/issues/22), [#23](https://github.com/h1alexbel/samples-filter/issues/23), [#24](https://github.com/h1alexbel/samples-filter/issues/24), [#9](https://github.com/h1alexbel/samples-filter/issues/9) are still not solved; solved: [#10](https://github.com/h1alexbel/samples-filter/issues/10), [#11](https://github.com/h1alexbel/samples-filter/issues/11), [#14](https://github.com/h1alexbel/samples-filter/issues/14), [#19](https://github.com/h1alexbel/samples-filter/issues/19).

**Comment by 0pdd** [comment]
@h1alexbel 4 puzzles [#18](https://github.com/h1alexbel/samples-filter/issues/18), [#22](https://github.com/h1alexbel/samples-filter/issues/22), [#24](https://github.com/h1alexbel/samples-filter/issues/24), [#9](https://github.com/h1alexbel/samples-filter/issues/9) are still not solved; solved: [#10](https://github.com/h1alexbel/samples-filter/issues/10), [#11](https://github.com/h1alexbel/samples-filter/issues/11), [#14](https://github.com/h1alexbel/samples-filter/issues/14), [#19](https://github.com/h1alexbel/samples-filter/issues/19), [#23](https://github.com/h1alexbel/samples-filter/issues/23).

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#18](https://github.com/h1alexbel/samples-filter/issues/18), [#22](https://github.com/h1alexbel/samples-filter/issues/22), [#9](https://github.com/h1alexbel/samples-filter/issues/9) are still not solved; solved: [#10](https://github.com/h1alexbel/samples-filter/issues/10), [#11](https://github.com/h1alexbel/samples-filter/issues/11), [#14](https://github.com/h1alexbel/samples-filter/issues/14), [#19](https://github.com/h1alexbel/samples-filter/issues/19), [#23](https://github.com/h1alexbel/samples-filter/issues/23), [#24](https://github.com/h1alexbel/samples-filter/issues/24).

**Comment by 0pdd** [comment]
@h1alexbel 4 puzzles [#18](https://github.com/h1alexbel/samples-filter/issues/18), [#22](https://github.com/h1alexbel/samples-filter/issues/22), [#43](https://github.com/h1alexbel/samples-filter/issues/43), [#9](https://github.com/h1alexbel/samples-filter/issues/9) are still not solved; solved: [#10](https://github.com/h1alexbel/samples-filter/issues/10), [#11](https://github.com/h1alexbel/samples-filter/issues/11), [#14](https://github.com/h1alexbel/samples-filter/issues/14), [#19](https://github.com/h1alexbel/samples-filter/issues/19), [#23](https://github.com/h1alexbel/samples-filter/issues/23), [#24](https://github.com/h1alexbel/samples-filter/issues/24).

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#18](https://github.com/h1alexbel/samples-filter/issues/18), [#22](https://github.com/h1alexbel/samples-filter/issues/22), [#43](https://github.com/h1alexbel/samples-filter/issues/43) are still not solved; solved: [#10](https://github.com/h1alexbel/samples-filter/issues/10), [#11](https://github.com/h1alexbel/samples-filter/issues/11), [#14](https://github.com/h1alexbel/samples-filter/issues/14), [#19](https://github.com/h1alexbel/samples-filter/issues/19), [#23](https://github.com/h1alexbel/samples-filter/issues/23), [#24](https://github.com/h1alexbel/samples-filter/issues/24), [#9](https://github.com/h1alexbel/samples-filter/issues/9).

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#62](https://github.com/h1alexbel/samples-filter/issues/62), [#63](https://github.com/h1alexbel/samples-filter/issues/63) are still not solved; solved: [#10](https://github.com/h1alexbel/samples-filter/issues/10), [#11](https://github.com/h1alexbel/samples-filter/issues/11), [#14](https://github.com/h1alexbel/samples-filter/issues/14), [#18](https://github.com/h1alexbel/samples-filter/issues/18), [#19](https://github.com/h1alexbel/samples-filter/issues/19), [#22](https://github.com/h1alexbel/samples-filter/issues/22), [#23](https://github.com/h1alexbel/samples-filter/issues/23), [#24](https://github.com/h1alexbel/samples-filter/issues/24), [#43](https://github.com/h1alexbel/samples-filter/issues/43), [#9](https://github.com/h1alexbel/samples-filter/issues/9).

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#63](https://github.com/h1alexbel/samples-filter/issues/63) is still not solved; solved: [#10](https://github.com/h1alexbel/samples-filter/issues/10), [#11](https://github.com/h1alexbel/samples-filter/issues/11), [#14](https://github.com/h1alexbel/samples-filter/issues/14), [#18](https://github.com/h1alexbel/samples-filter/issues/18), [#19](https://github.com/h1alexbel/samples-filter/issues/19), [#22](https://github.com/h1alexbel/samples-filter/issues/22), [#23](https://github.com/h1alexbel/samples-filter/issues/23), [#24](https://github.com/h1alexbel/samples-filter/issues/24), [#43](https://github.com/h1alexbel/samples-filter/issues/43), [#62](https://github.com/h1alexbel/samples-filter/issues/62), [#9](https://github.com/h1alexbel/samples-filter/issues/9).
