### ISSUE TITLE
Integrate multiple models in CLI

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/samples-filter#105]
Let's give ability to users to decide which model to use: Transformer or RF (via `--model`)

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#107](https://github.com/h1alexbel/samples-filter/issues/107) is still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#107](https://github.com/h1alexbel/samples-filter/issues/107), [#109](https://github.com/h1alexbel/samples-filter/issues/109) are still not solved.

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.4.0`

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#107](https://github.com/h1alexbel/samples-filter/issues/107), [#113](https://github.com/h1alexbel/samples-filter/issues/113) are still not solved; solved: [#109](https://github.com/h1alexbel/samples-filter/issues/109).
