### ISSUE TITLE
Investigate models based on unsupervised learning

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/samples-filter#129]
Let's investigate models like [Anomaly detection](https://en.wikipedia.org/wiki/Anomaly_detection) and text transformers that are based on unsupervised learning

**Comment by h1alexbel** [comment]
for classic ML unsupervised learning algorithms let's try [Clustering](https://en.wikipedia.org/wiki/Cluster_analysis). Some of the application contain these models:

* Hiearchical clustering - connectivity based clustering
* K-means clustering - centroid based clustering
* Principal Component Analysis (PCA)
* Singular Value Decomposition (SVD)
* Independent Component Analysis (ICA)
* Gaussian Mixture Models (GMM) - model based clustering
* Density-Based Spatial Clustering of Applications with Noise (DBSCAN) - densitiy based clustering

let's study them and pick one of them, that mostly applicable for our use-case

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#139](https://github.com/h1alexbel/samples-filter/issues/139) is still not solved.

**Comment by h1alexbel** [comment]
for transformers we trying BERT and SRdT (custom one)

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#139](https://github.com/h1alexbel/samples-filter/issues/139), [#154](https://github.com/h1alexbel/samples-filter/issues/154) are still not solved.
