### ISSUE TITLE
Dockerize models training

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/samples-filter#143]
let's wrap model training in deployable docker container

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#153](https://github.com/h1alexbel/samples-filter/issues/153) is still not solved.

**Comment by 0pdd** [comment]
@h1alexbel the only puzzle [#153](https://github.com/h1alexbel/samples-filter/issues/153) is solved here.
