### ISSUE TITLE
Train classification model on hugging face

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/samples-filter#30]
Let's train classification model on [huggingface](https://huggingface.co)

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#34](https://github.com/h1alexbel/samples-filter/issues/34), [#35](https://github.com/h1alexbel/samples-filter/issues/35) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#38](https://github.com/h1alexbel/samples-filter/issues/38), [#39](https://github.com/h1alexbel/samples-filter/issues/39) are still not solved; solved: [#34](https://github.com/h1alexbel/samples-filter/issues/34), [#35](https://github.com/h1alexbel/samples-filter/issues/35).

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#39](https://github.com/h1alexbel/samples-filter/issues/39), [#45](https://github.com/h1alexbel/samples-filter/issues/45), [#46](https://github.com/h1alexbel/samples-filter/issues/46) are still not solved; solved: [#34](https://github.com/h1alexbel/samples-filter/issues/34), [#35](https://github.com/h1alexbel/samples-filter/issues/35), [#38](https://github.com/h1alexbel/samples-filter/issues/38).

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#39](https://github.com/h1alexbel/samples-filter/issues/39), [#46](https://github.com/h1alexbel/samples-filter/issues/46), [#52](https://github.com/h1alexbel/samples-filter/issues/52) are still not solved; solved: [#34](https://github.com/h1alexbel/samples-filter/issues/34), [#35](https://github.com/h1alexbel/samples-filter/issues/35), [#38](https://github.com/h1alexbel/samples-filter/issues/38), [#45](https://github.com/h1alexbel/samples-filter/issues/45).

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#39](https://github.com/h1alexbel/samples-filter/issues/39), [#52](https://github.com/h1alexbel/samples-filter/issues/52) are still not solved; solved: [#34](https://github.com/h1alexbel/samples-filter/issues/34), [#35](https://github.com/h1alexbel/samples-filter/issues/35), [#38](https://github.com/h1alexbel/samples-filter/issues/38), [#45](https://github.com/h1alexbel/samples-filter/issues/45), [#46](https://github.com/h1alexbel/samples-filter/issues/46).

**Comment by 0pdd** [comment]
@h1alexbel all 7 puzzles are solved here: [#34](https://github.com/h1alexbel/samples-filter/issues/34), [#35](https://github.com/h1alexbel/samples-filter/issues/35), [#38](https://github.com/h1alexbel/samples-filter/issues/38), [#39](https://github.com/h1alexbel/samples-filter/issues/39), [#45](https://github.com/h1alexbel/samples-filter/issues/45), [#46](https://github.com/h1alexbel/samples-filter/issues/46), [#52](https://github.com/h1alexbel/samples-filter/issues/52).
