### ISSUE TITLE
dataset.py:51-57: CSV column 'readme' is too big to read...

### ISSUE THREAD

**Issue by 0pdd** [h1alexbel/samples-filter#39]
The puzzle `34-c96d2341` from #34 has to be resolved: 

https://github.com/h1alexbel/samples-filter/blob/fe282eb1951bd0c3d971d051a5b7952817b3b785/objects/dataset.py#L51-L57

The puzzle was created by @rultor on 19-Apr-24. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
Let's try pandas dataframes

**Comment by 0pdd** [comment]
The puzzle `34-c96d2341` has disappeared from the source code, that's why I closed this issue.
