### ISSUE TITLE
Pipeline for dataset building

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/samples-filter#41]
Let's formalize the pipeline for building train dataset. Here are the steps:

* pull `discover-repos.rb` script from [here](https://github.com/yegor256/cam/blob/master/steps/discover-repos.rb)
* run it 4 times with: 1) default params; 2) examples query + `--min-stars=25`; 3) samples query + `--min-stars=25`; 4) tutorials query + `--min-stars=25`
* combine all them into `merge.csv` (let's put this step into `combine.py`)
* clean dataset in `clean.py`, the result of this step should be _new_ `clean.csv` file
* label dataset with the help of `label.py` (ideally at this step we should create a new file too, however, it can be difficult to achieve this since copying `readme` column can [this](https://github.com/h1alexbel/samples-filter/issues/39) problem.
* version it (put current date or timestamp)
* upload train.csv into hugging face datasets repo

let's put all the source code related to that into `/dataset` folder.

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#44](https://github.com/h1alexbel/samples-filter/issues/44) is still not solved.

**Comment by 0pdd** [comment]
@h1alexbel the only puzzle [#44](https://github.com/h1alexbel/samples-filter/issues/44) is solved here.
