### ISSUE TITLE
train.py:44-49: Train model on target columns instead...

### ISSUE THREAD

**Issue by 0pdd** [h1alexbel/samples-filter#52]
The puzzle `45-34bf1ac1` from #45 has to be resolved: 

https://github.com/h1alexbel/samples-filter/blob/7d238e9db3b17a4e9dc4af256e1eeeab09e7adb2/model/train.py#L44-L49

The puzzle was created by @rultor on 24-Apr-24. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
Let's try these strategies:

* build single text input from all column values and feed it to the model: `input=repo is  $full_name, description: $description, topics:  $topics`;
* train model on multiple columns: `full_name`, `description`, `topics` and probably `readme`

**Comment by 0pdd** [comment]
The puzzle `45-34bf1ac1` has disappeared from the source code, that's why I closed this issue.
