### ISSUE TITLE
Investigate learning algorithm for real/sample repo classification

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/samples-filter#75]
Let's investigate learning algorithm and process for our classification task. This step is crucial to gather fundemental understanding what is the process of learning and how classification will work inside the algorithm.

**Comment by h1alexbel** [comment]
Some of these algorithms I found so far:
* Logistic Regression: Simple and effective for binary classification tasks. ?
* Support Vector Machines (SVM): Works well for both linear and non-linear classification. ?
* Decision Trees: Can handle both categorical and numerical data. ?
* Random Forest: An ensemble method that combines multiple decision trees. ?
* K-Nearest Neighbours (KNN): ?

**Comment by h1alexbel** [comment]
Let's investigate the _fundamental difference_ between **LR**, **RF** and **KNN** algorithms, and what is the best option for our use-case

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#81](https://github.com/h1alexbel/samples-filter/issues/81), [#82](https://github.com/h1alexbel/samples-filter/issues/82) are still not solved.

**Comment by h1alexbel** [comment]
I performed a small comparison on traditional ML classification algorithms vs. HuggingFace Transformers used for text-classification. The key difference to my knowledge, is in the _data format_ that we should provide to the model during the training stage. For instance, for RF (Random Forest) we can provide these information:

* `full_name`
* `description`
* `created_at`
* `last_commit`
* `readme`
* `label`

model, with the help of RF learning algorithm, will build the trees based on these data and marked `label` value for each that row. To me, it's more flexible approach for our case, since we can use **not only text data**, but numeric and other data too.

When it comes to the text transformers like HuggingFace, they accept **only text** and can reason about text data. In our case it's a `readme`. So dataset we would provide to such model will look like this:

* `readme`
* `label`

model, using [deep learning]() and [self-attention mechanisms]() would learn the textfield READMEs together with their 
marked labels. This approach is quite powerful, more resource-needed and to me looks less flexible.

**Comment by h1alexbel** [comment]
RQ2: What is the more performant in classification way? Machine Learning RF algorithm vs. transformers

**Comment by 0pdd** [comment]
@h1alexbel 5 puzzles [#81](https://github.com/h1alexbel/samples-filter/issues/81), [#82](https://github.com/h1alexbel/samples-filter/issues/82), [#88](https://github.com/h1alexbel/samples-filter/issues/88), [#89](https://github.com/h1alexbel/samples-filter/issues/89), [#90](https://github.com/h1alexbel/samples-filter/issues/90) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 4 puzzles [#81](https://github.com/h1alexbel/samples-filter/issues/81), [#82](https://github.com/h1alexbel/samples-filter/issues/82), [#89](https://github.com/h1alexbel/samples-filter/issues/89), [#90](https://github.com/h1alexbel/samples-filter/issues/90) are still not solved; solved: [#88](https://github.com/h1alexbel/samples-filter/issues/88).

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#81](https://github.com/h1alexbel/samples-filter/issues/81), [#82](https://github.com/h1alexbel/samples-filter/issues/82) are still not solved; solved: [#88](https://github.com/h1alexbel/samples-filter/issues/88), [#89](https://github.com/h1alexbel/samples-filter/issues/89), [#90](https://github.com/h1alexbel/samples-filter/issues/90).

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#119](https://github.com/h1alexbel/samples-filter/issues/119), [#81](https://github.com/h1alexbel/samples-filter/issues/81), [#82](https://github.com/h1alexbel/samples-filter/issues/82) are still not solved; solved: [#104](https://github.com/h1alexbel/samples-filter/issues/104), [#88](https://github.com/h1alexbel/samples-filter/issues/88), [#89](https://github.com/h1alexbel/samples-filter/issues/89), [#90](https://github.com/h1alexbel/samples-filter/issues/90).

**Comment by 0pdd** [comment]
@h1alexbel all 7 puzzles are solved here: [#104](https://github.com/h1alexbel/samples-filter/issues/104), [#119](https://github.com/h1alexbel/samples-filter/issues/119), [#81](https://github.com/h1alexbel/samples-filter/issues/81), [#82](https://github.com/h1alexbel/samples-filter/issues/82), [#88](https://github.com/h1alexbel/samples-filter/issues/88), [#89](https://github.com/h1alexbel/samples-filter/issues/89), [#90](https://github.com/h1alexbel/samples-filter/issues/90).
