### ISSUE TITLE
random-forest.py:80-83: Upload model and vectorizer as...

### ISSUE THREAD

**Issue by 0pdd** [h1alexbel/samples-filter#90]
The puzzle `75-e88026eb` from #75 has to be resolved: 

https://github.com/h1alexbel/samples-filter/blob/a40ba4825cb1ff46a63f408757ecaea71cd59652/model/rf/random-forest.py#L80-L83

The puzzle was created by @rultor on 06-May-24. 

Estimate: 40 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
HuggingFace does not support `.joblib` files. We can't upload it there, let's try S3 or `gh-pages` branch in this repo

**Comment by 0pdd** [comment]
The puzzle `75-e88026eb` has disappeared from the source code, that's why I closed this issue.
